### ISSUE TITLE
Check for multiple labels?

### ISSUE THREAD

**Issue by truthdoug** [cchantep/probot-pr-status-label#67]
Is it possible for this to check for more than one label?

For example, I'd a like a reviewer to verify that the PR has been reviewed for our code style and for our security checklist. I'd create labels "🔒  security ok" and "🕴️ code style ok" and I'd like both to be in place in order to approve the PR.

**Comment by matthewwo** [comment]
I think you'd define this in the regex to match the both labels. For example:

```
{
  "requiredStatusRegex": "^:[^:]+: ([^:]+):required$",
  "pendingStatusRegex": "^:[^:]+: ([^:]+):(?:security ok|code style ok)$",
  "successStatusRegex": "^:[^:]+: ([^:]+):(?:ok|success)$",
  "errorStatusRegex": "^:[^:]+: ([^:]+):(ko|error)$"
}
```

**Comment by truthdoug** [comment]
Thanks... I'll try that after I get the core functionality working.

**Comment by truthdoug** [comment]
I ended up switching to https://github.com/agilepathway/label-checker - it supports variations like `any_of`, `all_of`, and `none_of` to provide this functionality.
